Repository nishiki-tech/nishiki-backend, pull requests merged in 2023-10, with the labels that each got.

#8 add templates
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: task

#24 Feature/15 create the user context
  backend/main/package-lock.json
  backend/main/package.json
  backend/main/src/Shared/DDDPrimitive/AggrigateRoot.ts
  backend/main/src/Shared/DDDPrimitive/Entity.ts
  backend/main/src/Shared/Layers/Controller/Controller.ts
  backend/main/src/Shared/Layers/Controller/LambdaUrlHttpResponse.ts
  backend/main/src/Shared/Layers/UseCase/IUseCase.ts
  backend/main/src/Shared/Layers/UseCase/UseCase.ts
  backend/main/src/Shared/Layers/index.ts
  backend/main/src/Shared/Utils/Errors.ts
  backend/main/src/Shared/Utils/Result.ts
  backend/main/src/Shared/Utils/index.ts
  backend/main/src/Shared/index.ts
  backend/main/src/User/Controllers/CreateUserController.ts
  backend/main/src/User/Controllers/UpdateUserNameUseCaseController.ts
  backend/main/src/User/Domain/IUserRepository.ts
  backend/main/src/User/Domain/User.ts
  backend/main/src/User/Dtos/UserDto.ts
  backend/main/src/User/Repositories/UserRepository.ts
  backend/main/src/User/UseCases/CreateUserUseCase/CreateUserUseCase.ts
  backend/main/src/User/UseCases/CreateUserUseCase/ICreateUserUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/IUpdateUserNameUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/UpdateUserNameUseCase.ts
  backend/main/src/User/index.ts
  backend/main/test/Shared/Utils/Errors.test.ts
  backend/main/test/User/Domain/User.test.ts
  backend/main/test/User/MockUser.ts
  backend/main/test/User/MockUserRepository.ts
  backend/main/test/User/UseCases/CreateUserRepository.test.ts
  backend/main/test/User/UseCases/UpdateUserNameUseCase.test.ts
Labels: task

#26 Add a linter
  .github/workflows/lint.yml
  README.md
  backend/main/README.md
  backend/main/biome.json
  backend/main/package-lock.json
  backend/main/src/Shared/DDDPrimitive/AggrigateRoot.ts
  backend/main/src/Shared/DDDPrimitive/Entity.ts
  backend/main/src/Shared/DDDPrimitive/Identifier.ts
  backend/main/src/Shared/DDDPrimitive/ValueObject.ts
  backend/main/src/Shared/DDDPrimitive/index.ts
  backend/main/src/Shared/Layers/Controller/Controller.ts
  backend/main/src/Shared/Layers/Controller/LambdaUrlHttpResponse.ts
  backend/main/src/Shared/Layers/UseCase/IUseCase.ts
  backend/main/src/Shared/Layers/UseCase/UseCase.ts
  backend/main/src/Shared/Layers/index.ts
  backend/main/src/Shared/Utils/Errors.ts
  backend/main/src/Shared/Utils/Result.ts
  backend/main/src/Shared/Utils/index.ts
  backend/main/src/Shared/index.ts
  backend/main/src/User/Controllers/CreateUserController.ts
  backend/main/src/User/Controllers/UpdateUserNameUseCaseController.ts
  backend/main/src/User/Domain/IUserRepository.ts
  backend/main/src/User/Domain/User.ts
  backend/main/src/User/Dtos/UserDto.ts
  backend/main/src/User/Repositories/UserRepository.ts
  backend/main/src/User/UseCases/CreateUserUseCase/CreateUserUseCase.ts
  backend/main/src/User/UseCases/CreateUserUseCase/ICreateUserUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/IUpdateUserNameUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/UpdateUserNameUseCase.ts
  backend/main/src/User/index.ts
  backend/main/src/handler.ts
  backend/main/test/Shared/DDDPrimitives/Entity.test.ts
  backend/main/test/Shared/DDDPrimitives/Identifier.test.ts
  backend/main/test/Shared/DDDPrimitives/ValueObject.test.ts
  backend/main/test/Shared/Utils/Errors.test.ts
  backend/main/test/Shared/testData/identifierTestData.ts
  backend/main/test/User/Domain/User.test.ts
  backend/main/test/User/MockUser.ts
  backend/main/test/User/MockUserRepository.ts
  backend/main/test/User/UseCases/CreateUserRepository.test.ts
  backend/main/test/User/UseCases/UpdateUserNameUseCase.test.ts
  backend/main/vitest.config.ts
  biome.json
  cdk/bin/nishikiBackend.ts
  cdk/lib/nishikiBackend-stack.ts
  cdk/test/nishikiBackend-stack.test.ts
Labels: enhancement

#36 Add multiple issue templates under .github/ directory
  .github/ISSUE_TEMPLATE/bug_comunity.md
  .github/ISSUE_TEMPLATE/bug_team.md
  .github/ISSUE_TEMPLATE/feature_comunity.md
  .github/ISSUE_TEMPLATE/feature_team.md
  .github/ISSUE_TEMPLATE/question_comunity.md
  .github/ISSUE_TEMPLATE/question_team.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/ISSUE_TEMPLATE.md
Labels: documentation, internal

#37 Create CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation, internal

#38 marge develop branch
  .github/ISSUE_TEMPLATE/bug_comunity.md
  .github/ISSUE_TEMPLATE/bug_team.md
  .github/ISSUE_TEMPLATE/feature_comunity.md
  .github/ISSUE_TEMPLATE/feature_team.md
  .github/ISSUE_TEMPLATE/question_comunity.md
  .github/ISSUE_TEMPLATE/question_team.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yml
  .gitignore
  README.md
  backend/main/README.md
  backend/main/biome.json
  backend/main/docker-compose.yml
  backend/main/package-lock.json
  backend/main/package.json
  backend/main/src/Shared/DDDPrimitive/AggrigateRoot.ts
  backend/main/src/Shared/DDDPrimitive/Entity.ts
  backend/main/src/Shared/DDDPrimitive/Identifier.ts
  backend/main/src/Shared/DDDPrimitive/ValueObject.ts
  backend/main/src/Shared/DDDPrimitive/index.ts
  backend/main/src/Shared/Layers/Controller/Controller.ts
  backend/main/src/Shared/Layers/Controller/LambdaUrlHttpResponse.ts
  backend/main/src/Shared/Layers/UseCase/IUseCase.ts
  backend/main/src/Shared/Layers/UseCase/UseCase.ts
  backend/main/src/Shared/Layers/index.ts
  backend/main/src/Shared/Utils/Errors.ts
  backend/main/src/Shared/Utils/Result.ts
  backend/main/src/Shared/Utils/index.ts
  backend/main/src/Shared/index.ts
  backend/main/src/User/Controllers/CreateUserController.ts
  backend/main/src/User/Controllers/UpdateUserNameUseCaseController.ts
  backend/main/src/User/Domain/IUserRepository.ts
  backend/main/src/User/Domain/User.ts
  backend/main/src/User/Dtos/UserDto.ts
  backend/main/src/User/Repositories/UserRepository.ts
  backend/main/src/User/UseCases/CreateUserUseCase/CreateUserUseCase.ts
  backend/main/src/User/UseCases/CreateUserUseCase/ICreateUserUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/IUpdateUserNameUseCase.ts
  backend/main/src/User/UseCases/UpdateUserUseCase/UpdateUserNameUseCase.ts
  backend/main/src/User/index.ts
  backend/main/src/handler.ts
  backend/main/test/Shared/DDDPrimitives/Entity.test.ts
  backend/main/test/Shared/DDDPrimitives/Identifier.test.ts
  backend/main/test/Shared/DDDPrimitives/ValueObject.test.ts
  backend/main/test/Shared/Utils/Errors.test.ts
  backend/main/test/Shared/testData/identifierTestData.ts
  backend/main/test/User/MockUser.ts
  backend/main/test/User/MockUserRepository.ts
  backend/main/test/User/UseCases/CreateUserRepository.test.ts
  backend/main/test/User/UseCases/UpdateUserNameUseCase.test.ts
  backend/main/tsconfig.json
  backend/main/typedoc.json
  backend/main/vitest.config.ts
  biome.json
  cdk/bin/nishikiBackend.ts
  cdk/lib/nishikiBackend-stack.ts
  cdk/test/cdk.test.ts
  cdk/test/nishikiBackend-stack.test.ts
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE.md
Labels: documentation, enhancement

#47 Add commit convention guidelines to CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation, internal

#48 Update commit message convention in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation, internal

#52 Add GitHub Actions workflow for testing on pull requests
  .github/workflows/test.yml
Labels: enhancement, internal

#61 Feature/33 create a food object
  backend/main/src/Group/Domain/Entities/Food.ts
  backend/main/src/Group/Domain/ValueObjects/Expiry.ts
  backend/main/src/Group/Domain/ValueObjects/Quantity.ts
  backend/main/src/Group/Domain/ValueObjects/Unit.ts
  backend/main/test/Group/Domain/Entities/Food.test.ts
  backend/main/test/Group/Domain/ValueObjects/Expiry.test.ts
  backend/main/test/Group/Domain/ValueObjects/Quantity.test.ts
  backend/main/test/Group/Domain/ValueObjects/Unit.test.ts
Labels: enhancement

#58 feature: added a default name
  backend/main/src/User/Domain/Entity/User.ts
  backend/main/src/User/Domain/IUserRepository.ts
  backend/main/src/User/Domain/ValueObject/Username.ts
  backend/main/src/User/Dtos/UserDto.ts
  backend/main/src/User/Repositories/UserRepository.ts
  backend/main/src/User/UseCases/CreateUserUseCase/CreateUserUseCase.ts
  backend/main/src/User/UseCases/CreateUserUseCase/ICreateUserUseCase.ts
  backend/main/src/User/index.ts
  backend/main/test/User/Domain/Entity/User.test.ts
  backend/main/test/User/Domain/User.test.ts
  backend/main/test/User/Domain/ValueObject/Username.test.ts
Labels: enhancement, internal
